import Head from "next/head";
import { lazy, Suspense, useState } from "react";
import { Spinner } from "@diplomski/components/Spinner";
import { Props as VenueListItemProps } from "@diplomski/components/Venue/VenueListItem";

const Map = lazy(() => import("@diplomski/components/Map"));
const VenueListItem = lazy(
  () => import("@diplomski/components/Venue/VenueListItem")
);

export default function Home() {
  const [visibleVenues, setVisibleVenues] = useState<
    VenueListItemProps["venue"][]
  >([]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Suspense fallback={<Spinner />}>
        <div className="flex text-white">
          <div className="w-1/2 p-2 overflow-y-auto">
            <h2 className="text-2xl font-bold mb-2">
              Venues currently visible on map
            </h2>
            <div className="flex flex-col gap-2">
              {visibleVenues.length > 0 ? (
                visibleVenues.map((venue) => (
                  <VenueListItem key={venue.id} venue={venue} />
                ))
              ) : (
                <span className="text-gray-500">No venues visible</span>
              )}
            </div>
          </div>
          <div className="w-1/2">
            <Map onChangeVisibleVenues={setVisibleVenues} />
          </div>
        </div>
      </Suspense>
    </>
  );
}
